import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <meta name="description" content={String(metadata.description)} />
        <title>{String(metadata.title)}</title>
      </head>
      <body
        className={"flex flex-col items-center justify-center min-h-screen bg-green-950 text-white"}
      >
        {children}
        <footer className="mt-auto">
          Alex has a great footer
        </footer>
      </body>
    </html>
  );
}
